version: '3.8'

services:
  django:
    container_name: cserver
    build: 
      context: ./backend
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend:/usr/src/app/
    ports:
      - "8000:8000"
    env_file:
      - ./.env.dev
    depends_on:
      - db
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.dev
    ports:
      - "5433:5432"

  frontend:
    container_name: frontend
    build: 
      context: ./creole-frontend
    volumes:
      - ./creole-frontend:/usr/src/app/
    ports:
      - "5173:5173"
    command: npm run dev --host

volumes:
  postgres_data: